# Generated by Django 4.1.2 on 2022-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
